language: node_js
node_js:
- 0.10
deploy:
  provider: heroku
  api_key:
    secure: P/aeYMBJFvJN7jDXSR5zwrWlbeLRtM+CzTW16aFe51Rotd09cnvFb//p9su5uoTE4zmx1AHWK/ZxPqutcu10qrKXcO7jOfvMYtWgDxIR+aSVPyZse9JxLA5YDACVOMmTE52A7YmXqwqCUvxqMD1b0+P3QSr/Y8szjfverd5sSMc=
  app: request-inspect
  on:
    repo: johanneswuerbach/request-inspect
